### ISSUE TITLE
First time sign in when 2FA is forced QR code not recognized/wrong generated

### ISSUE THREAD

**Issue by Koky999** [nextcloud/twofactor_totp#1161]
### Steps to reproduce
1. Force 2FA in admin
2. Login as user
3. Try to scan QR code shown when first log in after force 2FA applied

### Expected behaviour
After scanning code with TOTP app it should add generator to the app.

### Actual behaviour
When user sign in, QR code show up, if I scan it with TOTP app (tried Google Authenticator and andOTP) but app fails with message "Cannot recognize the code". Barcode probably wrong generated, because it has only text "undefined" in in.

![alt text](https://i.imgur.com/ES1xHho.jpeg)

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** mysql 5.5.60

**PHP version:** 7.4.25

**Version:** 22.2.3

**Updated from an older version or fresh install:** Updated from older version

**List of activated apps:**

Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - apporder: 0.13.0
  - bruteforcesettings: 2.2.0
  - camerarawpreviews: 0.7.15
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - external: 3.9.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_downloadactivity: 1.11.1
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_texteditor: 2.14.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - guests: 2.1.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - side_menu: 2.0.1
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - theming_customcss: 1.10.0
  - twofactor_admin: 3.1.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_email: 2.1.1
  - twofactor_totp: 6.1.0
  - updatenotification: 1.12.0
  - user_ldap: 1.12.1
  - user_usage_report: 1.6.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0

Disabled:
  - dashboard
  - encryption
  - registration
  - twofactor_gateway
  - user_status
  - weather_status

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:** Firefox 78.7.1esr

**Operating system:** Windows 10

**Comment by ChristophWurst** [comment]
Fixed with https://github.com/nextcloud/server/pull/29752. https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/29763.patch is the patch for your version of the Nextcloud server.

**Comment by Koky999** [comment]
@ChristophWurst Thank you very much Christoph and sorry fot this topic. But maybe stupid question. What to do next after patching? I restarted httpd service and still same. First time patching something in linux...

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html covers the process

**Comment by Koky999** [comment]
Yes, I used this. 

From install folder patch -p 1 < /tmp/29763.patch i got
patching file core/Controller/OCJSController.php
patching file core/Middleware/TwoFactorMiddleware.php

After that no change. I tried restart apache, no change. Restarted whole server, no change. Still wrong undefined QR code.

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/twofactor_totp/issues/1147#issuecomment-970007259.

Is the request to `/enable` successful? It returns the information for the QR code.

**Comment by Koky999** [comment]
Something from this? I think it is succesful (state 1) but not QrUrl or secret there.
![Snímek obrazovky (1063)](https://user-images.githubusercontent.com/95216917/143882252-7438818d-a2fe-4fbd-8974-8f7096003472.png)
![Snímek obrazovky (1064)](https://user-images.githubusercontent.com/95216917/143882257-082fe36e-c54c-4809-afa3-270dfd6ddb44.png)
![Snímek obrazovky (1065)](https://user-images.githubusercontent.com/95216917/143882256-d9b76370-7bd5-41b1-b14d-32f99e3a9113.png)

**Comment by ChristophWurst** [comment]
> not QrUrl or secret there

this is strange. could you show the HTTP status code and the response of the `enable` request?

if it return state 1 indeed then I don't see a way for secret or qr code to be empty https://github.com/nextcloud/twofactor_totp/blob/868e46da19968ff3ae45f0d9f2a821a82779f488/lib/Controller/SettingsController.php#L86-L96

**Comment by Koky999** [comment]
I don't know if I am in righ view. 
Status code 303
![image](https://user-images.githubusercontent.com/95216917/143889390-f954b6b4-5553-4d39-8f52-ddf354f2f035.png)

Response: Failed to load, redirected
![Snímek obrazovky (1073)](https://user-images.githubusercontent.com/95216917/143889619-fe142f30-94d1-4e50-93fa-e6ee576c3b8d.png)

**Comment by Koky999** [comment]
Well today I upgrade production version (this was copy of production) and there is everything okay with 2FA TOTP. Then sorry and can be closed I guess
